### ISSUE TITLE
Unraid Install Error: invalid volume specification

### ISSUE THREAD

**Issue by fkick** [CollinHeist/TitleCardMaker#177]
Unable to install on Unraid using the CA app installer/docker.  Getting the following Error:

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='TitleCardMaker' --net='host' -e TZ="America/Chicago" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="TitleCardMaker" -e 'TCM_PREFERENCES'='/config/preferences.yml' -e 'TCM_RUNTIME'='22:00' -e 'TCM_FREQUENCY'='12h' -e 'PGID'='314' -e 'PUID'='314' -e 'TCM_LOG'='INFO' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.icon='https://raw.githubusercontent.com/CollinHeist/TitleCardMaker/40d45900c8533ec18fa2ca6603923838930abe98/.github/logo.png' -l 'TCM_MISSING'='/config/missing.yml' -v '/mnt/user/appdata/TitleCardMaker':'/config':'rw' -v '':'/archive':'rw' -v '':'/source':'rw' -v '/mnt/user/appdata/TitleCardMaker/logs':'{1}':'rw' 'collinheist/titlecardmaker:master' 
docker: Error response from daemon: invalid volume specification: '/mnt/user/appdata/TitleCardMaker/logs:{1}:rw': invalid mount config for type "bind": invalid mount path: '{1}' mount path must be absolute.
See 'docker run --help'.

The command failed.
```

**Comment by CollinHeist** [comment]
Does the `/mnt/user/appdata/TitleCardMaker/logs` directory exist?

**Comment by CollinHeist** [comment]
Actually I think this is fixed, I'm just waiting for Unraid the CA store to pull in the changes. Try specifying `/mnt/user/appdata/TitleCardMaker/config` to `/config`, and `/mnt/user/appdata/TitleCardMaker/logs` to `/maker/logs`

Does that fix this?

**Comment by fkick** [comment]
Yes, the /mnt/user/appdata/TitleCardMaker/logs is created... and no, manually adding two path variables to define /config and /maker/logs does not fix the issue. I'm thinking there's an issue in the docker composer where it is specifying {1} in the mount path and it's not liking {1}

**Comment by CollinHeist** [comment]
Yeah I am not sure where that {1} is coming from. In the advanced dropdown, what do you have for the logs directory?

![Screen Shot 2022-06-13 at 2 04 44 PM](https://user-images.githubusercontent.com/17693271/173435788-76549cd1-3575-4fbf-af6c-bc8eedd6c7d7.jpg)

**Comment by fkick** [comment]
Interesting, I don't have a Log Directory path inside the advanced view:
<img width="1057" alt="Screen Shot 2022-06-13 at 3 06 51 PM" src="https://user-images.githubusercontent.com/8224667/173436200-bcb67f5b-aa04-4f51-b712-6d24baa7451e.png">

**Comment by CollinHeist** [comment]
Sorry, I mistyped/spoke, do `Show more settings ...` is it there?

**Comment by fkick** [comment]
No, I'm not seeing it when Show More Settings is enabled.

**Comment by CollinHeist** [comment]
Yeah if you could change that from `{1}` in the container path to `/maker/logs`, will you see if that fixes it? I've pushed a potential fix on the config, but I am at the whim of whenever update the CA

**Comment by fkick** [comment]
That did it. I'm now able to install. It won't start yet, but that's because I need to create teh preferences.yml etc

**Comment by CollinHeist** [comment]
Perfect. Thanks for pointing that out. I'll close this when I see it updated in the store. Hopefully I got that fixed

**Comment by fkick** [comment]
Once more small issue I noticed... the Configuration Path variable in the docker was set to /mnt/user/appdata/TitleCardMaker/ but should be set to /mnt/user/appdata/TitleCardMaker/config/

**Comment by subasically** [comment]
> Yeah if you could change that from `{1}` in the container path to `/maker/logs`, will you see if that fixes it? I've pushed a potential fix on the config, but I am at the whim of whenever they update the CA

This fixed it for me as well.
